# Auto-populated on 2026-06-05 from old UDP master snapshots

[[server]]
address  = "222.187.254.125:23015"
protocol = 49
contact  = "1033341124@qq.com"
host     = "[XXH] Zombie Crisis"

[[server]]
address  = "222.187.254.125:23016"
protocol = 49
contact  = "1033341124@qq.com"
host     = "[XXH] CSDM:FFA Qqun:434673380"

[[server]]
address  = "119.91.201.9:27015"
protocol = 49
host     = "--[R]--[Zombie 5.0]--(CF Hero) Level EXP--616117100"

[[server]]
address  = "167.235.7.101:27015"
protocol = 49
host     = "[FFA] Empty Protocol [CSDM]"

[[server]]
address  = "185.189.167.10:27015"
protocol = 49
host     = "r2d2 [yapb/arm64]"

[[server]]
address  = "188.212.103.154:27015"
protocol = 49
host     = "* BIO.DINSCURT.COM | Zombie-Strike"

[[server]]
address  = "217.154.211.69:27025"
protocol = 49
host     = "[CSVR] Classic CS 1.6 VR Server"

[[server]]
address  = "51.91.249.12:27015"
protocol = 49
host     = "[Lemita]:: CSDM (t.me/lemita_project)"

[[server]]
address  = "51.91.249.12:27016"
protocol = 49
host     = "[Lemita]:: TeamPlay"

[[server]]
address  = "72.60.130.39:27015"
protocol = 49
host     = "[IceEyes] CLASSIC PUBLIC (rank / vip system)"

[[server]]
address  = "82.77.209.165:27015"
protocol = 48
host     = "# LastCS.RO GunGame~AntiCheat~2xJump~SpawnProtect~1000FPS"

[[server]]
address  = "82.77.209.92:27015"
protocol = 48
host     = "# LastCS.RO Respawn~AntiCheat~2xJump~SpawnProtect~1000FPS"

[[server]]
address  = "82.77.209.95:27015"
protocol = 48
host     = "# LastCS.RO Zombie Swarm Defense~Knockback~Leap~1000FPS"

[[server]]
address  = "82.77.209.96:27015"
protocol = 49
host     = "# Cs.Lastcs.Ro#ClassicOldSchool~AntiCheat~WarmUp~SpawnProtect~1000FPS"

[[server]]
address  = "89.207.221.227:27015"
protocol = 49
host     = "[CSVR] Noname Server"

# Added on 2026-06-06 from a follow-up master dump
[[server]]
address  = "186.19.63.56:27015"
protocol = 49
contact  = "vladimiro75@gmail.com"
host     = "[ARG] Counter-Strike 1.6 Server +Bots"

[[server]]
address  = "5.196.165.2:27015"
protocol = 48
contact  = "t.me/czarintax"
host     = "OLD SCHOOL CS"

[[server]]
address  = "131.196.196.196:27020"
protocol = 48
contact  = "tobiascarlossoares@gmail.com, discord:yukihira9319"
host     = "Fantasy Gaming | Zombie Escape | FreeVIP+CSO+Events"

[[server]]
address  = "136.110.10.31:27015"
protocol = 49
contact  = "t.me/moha_kun , discord: mohmemes.dz"
host     = "CloverXD | Zombie Escape Mod [ViP | XP | CSO]"

[[server]]
address  = "168.222.251.98:6610"
protocol = 48
contact  = "tilinasowaza5@gmail.com"
host     = "Zombie Plague 4.3 Peru"

[[server]]
address  = "168.222.251.98:4728"
protocol = 48
contact  = "dark17780@gmail.com"
host     = "Zombie Escape"

[[server]]
address = "193.111.78.158:27015"
protocol = 49
contact = "barkinayaz9@gmail.com"
host = "[AYZ]Zombie Escape Reborn"

[[server]]
address  = "89.221.220.61:27017"
contact  = "info@goldsrc.one"
protocol = 48
host     = "[GoldSrc.one] CrossPlay (register at discord.goldsrc.one)"

[[server]]
address = "104.234.65.245:27300"
protocol = 48 
contact = "csnightkillers@gmail.com, discord:gelado710_, discord:hevy7229"
host = "[NIGHT KILLERS] | ZOMBIE PLAGUE | XP-LEVEL-FPS"

[[server]]
address  = "131.196.199.248:27015"
protocol = 48
contact  = "matheus.rondine@terra.com.br"
host     = "zS.TeaM"

[[server]]
address = "178.63.182.108:5606"
protocol = 48
contact = "nsabkelkiyed@gmail.com"
host = "Zombie Biohazard 6.3 [FREE VIP] + [Level Bank]"

[[server]]
address  = "9950x.mc5173.cn:27018"
protocol = 48
contact  = "1041936439@qq.com"
host     = "Zombie Nightmare v1.0"

[[server]]
address  = "91.151.88.240:27015"
protocol = 48
contact  = "satinthebox@gmail.com"
host   = "Dark Professional | Zombie Escape Updated! | FreeVIP+BOSS+Event"

[[server]]
address  = "132.243.253.240:2253"
protocol = 48
contact  = "rimage2024@gmail.com"
host   = "the liche family | Zombie escape "

[[server]]
address = "81.181.244.5:27015"
protocol = 48
contact = "info@csomod.com"
host = "[ZOMBIES]+[CSO MOD] [#1] CSOMOD.COM [since 2012]"

[[server]]
address  = "94.156.11.186:27020"
protocol = 48
contact  = "Discord: vx.moha"
host   = "Venom Xtreme | Zombie Escape | Naruto Shippuden"

[[server]]
address  = "192.168.1.195:27015"
protocol = 49
contact  = "zafreelab@gmail.com"
host     = "Counter Strike Advanced edition"
